import { NextResponse } from 'next/server';

export async function POST(req: Request) {
    try {
        const { transcript } = await req.json();

        if (!transcript || typeof transcript !== 'string') {
            return NextResponse.json({ error: 'Missing or invalid transcript' }, { status: 400 });
        }

        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            return NextResponse.json({ error: 'GEMINI_API_KEY is not configured' }, { status: 500 });
        }

        const prompt = `
You are an expert AI Medical Scribe. Your task is to process a raw transcript of a conversation between a doctor and a patient, and extract key medical information to populate an Electronic Medical Record (EMR).

Analyze the following transcript and extract the requested fields. Provide your response as a raw JSON object (without markdown code blocks) using the exact keys described below.

Transcript:
"""
${transcript}
"""

Required JSON output format:
{
  "complaint": "A concise summary of the History of Presenting Illness (HPI) and Chief Complaint.",
  "diagnosis": "The provisional clinical diagnosis based on the conversation. Include ICD-10 code if obvious, else write '(ICD-10 Pending)'.",
  "investigations": "Any tests, scans, or investigations the doctor ordered or suggested. If none, write 'None ordered'.",
  "medications": "A bulleted list of medications prescribed, including dosage and frequency.",
  "safetyFlags": "Any severe clinical safety flags, drug interactions, or important patient history warnings (like allergies or past conditions) mentioned. If none, return null."
}`;

        // Using standard fetch instead of the SDK to avoid npm install issues
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: prompt }]
                }],
                generationConfig: {
                    responseMimeType: "application/json",
                    temperature: 0.1
                }
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Gemini API Error: ${errorText}`);
        }

        const data = await response.json();
        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!generatedText) {
            throw new Error('No text generated by Gemini');
        }

        const parsedData = JSON.parse(generatedText);

        return NextResponse.json(parsedData);

    } catch (error: any) {
        console.error('Error generating summary:', error);
        return NextResponse.json({ error: error.message || 'Failed to generate summary' }, { status: 500 });
    }
}
